version: "3.2"
services:
  web_db:
    image: mysql:5.7.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    user: "${PROJECT_USER}"
    volumes:
      - "~/code/mysql:/var/lib/mysql"
      - type: volume
        source: dbdata
        target: /deltas/
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "website"
      MYSQL_USER: "jdoe"
      MYSQL_PASSWORD: "G^Bx7yedCTEM"
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      web_net:
        aliases:
          - database
  web_portal:
    image: web_portal
    command: python manage.py runserver 0.0.0.0:8000
    user: "${PROJECT_USER}"
    volumes:
      - "~/code/web_portal:/code"
      - "dbdata:/code/deltas"
    ports:
      - "8000:8000"
    depends_on:
      - web_db
    networks:
      - web_net

volumes:
  dbdata:

networks:
  web_net:

